#!/bin/sh

echo ""
echo "Packaging only for openwrt 22.03"
echo ""

rm -r build

mkdir -p build/etc                  \
         build/etc/qlimiter/kernel  \
         build/etc/qlimiter/scripts \
         build/etc/hotplug.d/iface

buildpath=./kernel/limit_s_da

make -C $buildpath clean
make -C $buildpath

cp $buildpath/*.o build/etc/qlimiter/kernel
cp scripts/* build/etc/qlimiter/scripts
chmod 755 build/etc/qlimiter/scripts/*

cat > build/etc/qlimiter/vars << EOF
# tc config
KERNEL_NAME=/etc/qlimiter/kernel/bpf.o
KERNEL_SECTION=limitator

#Format(classid:speed ...)
SPEEDS="AA:128Kbit 10:512Kbit 15:256Kbit"

#--------------------
IFACE=eth0
IFB_IFACE=ifb0

#Q_MODE, 1=Reset, 2=Add
Q_MODE=1

Q_SIZE=1073741824
MARK=0xAA
EOF

cat > build/etc/qlimiter/qsave << EOF
#!/bin/sh

cat /proc/net/xt_quota/quota > /etc/qcont

EOF
chmod 755 build/etc/qlimiter/qsave 

cat > build/etc/qlimiter/cfw << EOF
#!/bin/sh

. /etc/qlimiter/vars

nft --version > /dev/null 2>&1
if [ \$? -eq 0 ]; then
    . /etc/qlimiter/scripts/nft_create
else
    . /etc/qlimiter/scripts/ipt_create
fi

if [ -e "/etc/qcont" ]; then 
    cat /etc/qcont > /proc/net/xt_quota/quota
fi

EOF
chmod 755 build/etc/qlimiter/cfw 

cat > build/etc/qlimiter/resetq << EOF
#!/bin/sh

. /etc/qlimiter/vars

case \$Q_MODE in 
    2)
        let "Q_ADDED=`cat /proc/net/xt_quota/quota`+Q_SIZE"
        echo \$Q_ADDED > /proc/net/xt_quota/quota
    ;;
    *)
        echo \$Q_SIZE > /proc/net/xt_quota/quota
    ;;
esac

bpftool map update name f_map key hex fa fa 00 f0 value hex 00 00 00 00 exist

EOF
chmod 755 build/etc/qlimiter/resetq

cat > build/etc/qlimiter/srun << EOF
#!/bin/sh

. /etc/qlimiter/vars

SCRIPTPATH="\$(cd -- "\$(dirname "\$0")" >/dev/null 2>&1; pwd -P)"

#. \$SCRIPTPATH/scripts/openwrt_module_check

nft --version > /dev/null 2>&1
if [ \$? -eq 0 ]; then
    . \$SCRIPTPATH/scripts/nft_create
else
    . \$SCRIPTPATH/scripts/ipt_create
fi

. \$SCRIPTPATH/scripts/tc_create
EOF
chmod 755 build/etc/qlimiter/srun

cat > build/etc/hotplug.d/iface/80-tc_create << EOF
#!/bin/sh

. /etc/qlimiter/vars

if [ "\$ACTION" = "ifup" ]; then 
    if [ "\$DEVICE" = "\$IFACE" ]; then        
        . /etc/qlimiter/scripts/tc_create
    fi
fi
EOF

cp -r patches/* build/

tar zc -C build -f qlimiter.tar.gz --group=root:0 --owner=root:0 `ls build`
