#!/bin/sh

# tc config
KERNEL_NAME=./bpf_l.o
KERNEL_SECTION=limitator

SPEEDS="AA:128Kbit 10:512Kbit 15:256Kbit"

#--------------------
IFACE=enp0s7
IFB_IFACE=ifb0

Q_SIZE=1073741824

MARK=0xAA # using mark as classid

buildpath=./kernel/limit_s_da

rm *.o

make -C $buildpath clean
make -C $buildpath

cp $buildpath/*.o .

SCRIPTPATH=`realpath ./scripts`

#. ./scripts/openwrt_module_check

nft --version > /dev/null 2>&1
if [ $? -eq 0 ]; then
    . $SCRIPTPATH/nft_create
else
    . $SCRIPTPATH/ipt_create
fi

. $SCRIPTPATH/tc_create
