#!/bin/sh

ipt="iptables-nft"

if [ -d '/etc/qlimiter/scripts' ]; then
    . /etc/qlimiter/scripts/ipt_create
    done
fi

if [ -z $SCRIPTPATH ]; then
    SCRIPTFULLNAME=`realpath $0`
    SCRIPTPATH=`dirname $SCRIPTFULLNAME`    
fi

. $SCRIPTPATH/ipt_create

