#!/bin/sh

_tc="tc"

if [ -z "`lsmod | grep ifb`" ]; then
    modprobe ifb numifbs=1
fi

chfsc_class() {
    $_tc class add dev $1 parent $2: classid $2:$3 hfsc rt m2 $4
    $_tc qdisc add dev $1 parent $2:$3 handle 1$3: fq_codel
}

create_classes() {
    for p in $3; do
        local cid=`echo $p | awk -F: '{print $1; exit 0}'`
        local spd=`echo $p | awk -F: '{print $2; exit 0}'`
        chfsc_class $1 $2 $cid $spd
    done
}

ip link set dev $IFB_IFACE up

$_tc qdisc del dev $IFACE root handle 1: > /dev/null 2>&1 
$_tc qdisc del dev $IFB_IFACE root handle 1: > /dev/null 2>&1 
$_tc qdisc del dev $IFACE ingress > /dev/null 2>&1

$_tc qdisc add dev $IFACE root handle 1: hfsc default 1
create_classes $IFACE 1 "$SPEEDS"

$_tc filter add dev $IFACE parent 1: handle 77 protocol all prio 1 \
               bpf object-file $KERNEL_NAME section $KERNEL_SECTION da classid 1:1

$_tc qdisc add dev $IFACE handle ffff: ingress
$_tc filter add dev $IFACE parent ffff: protocol all \
        u32 match u32 0 0 action mirred egress redirect dev $IFB_IFACE

$_tc qdisc add dev $IFB_IFACE root handle 1: hfsc default 1
create_classes $IFB_IFACE 1 "$SPEEDS"

$_tc filter add dev $IFB_IFACE parent 1: handle 77 protocol all prio 1 \
               bpf object-file $KERNEL_NAME section $KERNEL_SECTION/ingress da classid 1:1

